import { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    name: 'Brand Theme - Energetic',
    category: 'Brand Theme',
    styleTags: ['upbeat', 'playful', 'energetic', 'children', 'friendly'],
    excludeTags: ['dark', 'sad', 'slow', 'aggressive'],
    sections: [
      { id: '1', type: 'Intro', instrument: 'kalimba hook' },
      { id: '2', type: 'Verse', instrument: 'ukulele' },
      { id: '3', type: 'Chorus', instrument: 'xylophone' },
      { id: '4', type: 'Bridge', instrument: 'ambient pad' },
      { id: '5', type: 'Outro', instrument: 'gentle chimes' },
    ],
    lyricPromptTemplate: '[Intro | kalimba hook]\n[Verse | ukulele]\n[Chorus | xylophone]\n[Bridge | ambient pad]\n[Outro | gentle chimes]',
  },
  {
    name: 'Brand Theme - Iconic Intro',
    category: 'Brand Theme',
    styleTags: ['iconic', 'memorable', 'bright', 'children', 'intro'],
    excludeTags: ['complex', 'long', 'dark'],
    sections: [
      { id: '1', type: 'Intro', instrument: 'kalimba hook' },
      { id: '2', type: 'Verse', instrument: 'ambient pad' },
      { id: '3', type: 'Hook', instrument: 'bright synth' },
    ],
    lyricPromptTemplate: '[Intro | kalimba hook]\n[Verse | ambient pad]\n[Hook | bright synth]',
  },
  {
    name: 'Lullaby - Soft Dreams',
    category: 'Lullaby',
    styleTags: ['gentle', 'soft', 'soothing', 'calm', 'slow', 'peaceful', 'lullaby'],
    excludeTags: ['loud', 'fast', 'energetic', 'harsh'],
    sections: [
      { id: '1', type: 'Intro', instrument: 'soft piano' },
      { id: '2', type: 'Verse', instrument: 'ambient pad' },
      { id: '3', type: 'Verse', instrument: 'music box' },
      { id: '4', type: 'Chorus', instrument: 'gentle strings' },
      { id: '5', type: 'Verse', instrument: 'ambient pad' },
      { id: '6', type: 'Verse', instrument: 'soft harp' },
      { id: '7', type: 'Bridge', instrument: 'gentle chimes' },
      { id: '8', type: 'Verse', instrument: 'music box' },
      { id: '9', type: 'Verse', instrument: 'ambient pad' },
      { id: '10', type: 'Chorus', instrument: 'gentle strings' },
      { id: '11', type: 'Verse', instrument: 'soft piano' },
      { id: '12', type: 'Outro', instrument: 'fading ambient' },
    ],
    lyricPromptTemplate: '[Intro | soft piano]\n[Verse | ambient pad]\n[Verse | music box]\n[Chorus | gentle strings]\n[Verse | ambient pad]\n[Verse | soft harp]\n[Bridge | gentle chimes]\n[Verse | music box]\n[Verse | ambient pad]\n[Chorus | gentle strings]\n[Verse | soft piano]\n[Outro | fading ambient]',
  },
  {
    name: 'Lullaby - Extended Peaceful',
    category: 'Lullaby',
    styleTags: ['peaceful', 'extended', 'calm', 'dreamy', 'soft', 'lullaby'],
    excludeTags: ['loud', 'fast', 'upbeat', 'complex'],
    sections: [
      { id: '1', type: 'Intro', instrument: 'music box' },
      { id: '2', type: 'Verse', instrument: 'soft strings' },
      { id: '3', type: 'Verse', instrument: 'ambient pad' },
      { id: '4', type: 'Verse', instrument: 'gentle harp' },
      { id: '5', type: 'Chorus', instrument: 'soft piano' },
      { id: '6', type: 'Verse', instrument: 'music box' },
      { id: '7', type: 'Verse', instrument: 'ambient pad' },
      { id: '8', type: 'Bridge', instrument: 'gentle chimes' },
      { id: '9', type: 'Verse', instrument: 'soft strings' },
      { id: '10', type: 'Verse', instrument: 'ambient pad' },
      { id: '11', type: 'Chorus', instrument: 'soft piano' },
      { id: '12', type: 'Verse', instrument: 'music box' },
      { id: '13', type: 'Verse', instrument: 'gentle harp' },
      { id: '14', type: 'Outro', instrument: 'fading ambient' },
    ],
    lyricPromptTemplate: '[Intro | music box]\n[Verse | soft strings]\n[Verse | ambient pad]\n[Verse | gentle harp]\n[Chorus | soft piano]\n[Verse | music box]\n[Verse | ambient pad]\n[Bridge | gentle chimes]\n[Verse | soft strings]\n[Verse | ambient pad]\n[Chorus | soft piano]\n[Verse | music box]\n[Verse | gentle harp]\n[Outro | fading ambient]',
  },
];

export const SECTION_TYPES = [
  'Intro',
  'Verse',
  'Chorus',
  'Bridge',
  'Hook',
  'Interlude',
  'Outro',
];

export const INSTRUMENT_OPTIONS = [
  'kalimba hook',
  'ukulele',
  'xylophone',
  'ambient pad',
  'gentle chimes',
  'soft piano',
  'music box',
  'gentle strings',
  'soft harp',
  'fading ambient',
  'bright synth',
  'soft strings',
  'marimba',
  'acoustic guitar',
  'celeste',
];

export const STYLE_TAG_SUGGESTIONS = [
  'upbeat',
  'playful',
  'energetic',
  'gentle',
  'soft',
  'soothing',
  'calm',
  'peaceful',
  'dreamy',
  'friendly',
  'bright',
  'iconic',
  'memorable',
  'slow',
  'lullaby',
  'children',
];

export const EXCLUDE_TAG_SUGGESTIONS = [
  'dark',
  'sad',
  'aggressive',
  'loud',
  'fast',
  'harsh',
  'complex',
  'long',
];
